In [1]:
import numpy as np

In [2]:
#create random genration 
x = np.random.rand(4)
print(x)

[0.47616887 0.93246455 0.63516537 0.66243734]


In [3]:
x = np.random.rand(1,10,23)
print(x)

[[[0.77329577 0.27539292 0.2862829  0.22346232 0.40472205 0.23754987
   0.16872164 0.15797849 0.79429067 0.56108544 0.39245093 0.12754753
   0.84956601 0.02684524 0.40363423 0.1582749  0.83035317 0.09664473
   0.42334673 0.23370035 0.59275318 0.21638477 0.58166355]
  [0.47815941 0.10388009 0.05225841 0.48381539 0.66268043 0.68706712
   0.70684141 0.43205055 0.54164879 0.68582368 0.16812182 0.43034287
   0.96826515 0.98259792 0.89723955 0.99805778 0.98707045 0.83042926
   0.92566592 0.52609992 0.62724504 0.13164261 0.77255807]
  [0.2019996  0.24388654 0.21932918 0.46177564 0.13917585 0.51243909
   0.21227142 0.27402875 0.99693477 0.89949922 0.24013431 0.07090041
   0.09820955 0.01334784 0.99371857 0.34492927 0.77206458 0.48859154
   0.11044683 0.79000745 0.85470806 0.94758115 0.98140934]
  [0.24331173 0.33994849 0.72001514 0.44489477 0.58023855 0.62788888
   0.34505242 0.05339086 0.79136776 0.40755169 0.80764017 0.86744249
   0.48961396 0.55480778 0.8485755  0.51508618 0.62240414 0.1881

In [5]:
x = np.random.randn(4)
print(x)

[-1.21401991 -0.3051645   0.03998899 -0.36999684]


In [8]:
xy= np.random.ranf(3) #this no will close to zero and less than 1
print(xy)   

[0.08174151 0.68930119 0.128115  ]


In [9]:
x = np.random.randint(1,9,6)
print(x)

[1 7 6 2 2 7]
