In [1]:
import numpy as np

In [5]:
l1 = [10,20,30]
l2 = [40,5,89]
a = np.array(l1)
b = np.array(l2)
print(a)
print(b)
print(a+b) #we can directly use maths functions in numpy but not in a list

[10 20 30]
[40  5 89]
[ 50  25 119]


In [3]:
import numpy as np
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr)

[[10 20 30 40]
 [50 60 70 80]]


In [4]:
#function of numpy

l1 = [10,20,30]
l2 = [40,5,89]
a = np.array(l1)
b = np.array(l2)
print(a)

[10 20 30]


In [5]:
print(a.shape)

(3,)


In [7]:
print(a.shape) #shape and dimention of array
print(len(a)) #Length of array
print(np.size(a)) #size of array
print(type(a)) #know data type of variable
print(a.dtype) # know data type
print(arr.astype(str)) #change type of array

(3,)
3
3
<class 'numpy.ndarray'>
int32
[['10' '20' '30' '40']
 ['50' '60' '70' '80']]


In [11]:
#maths opration 

l1 = [10,20,30]
l2 = [40,5,89]
a = np.array(l1)
b = np.array(l2)
print(a)
print(b)
print( )
print(a+b) #add arry

print(np.add(a,b))

print(a-b) #sub arry

print(np.subtract(a,b))

print(a*b) #multiply
print(a/b)
print(a^b)

[10 20 30]
[40  5 89]

[ 50  25 119]
[ 50  25 119]
[-30  15 -59]
[-30  15 -59]
[ 400  100 2670]
[0.25       4.         0.33707865]
[34 17 71]
